### PR TITLE
watir-webdriver has been retired

### PR DESCRIPTION
**Pull request by jancar59**
The watir-webdriver gem has been retired in favor of the watir 6.0 gem.

### CODE REVIEW

**Comment by jancar59** [comment]
How come the gems at rubydoc.info and rubygems.org haven't been updated?


—
Jan Carlsson, B3IT Init AB
Konsult Systemutveckling
jan.carlsson@b3it.se<mailto:calle.dybedahl@init.se> - 070-714 61 30


________________________________
Från: Abe Heward <notifications@github.com>
Skickat: den 24 januari 2018 15:48:53
Till: aheward/TestFactory
Kopia: Jan Carlsson; Author
Ämne: Re: [aheward/TestFactory] watir-webdriver has been retired (#1)


Merged #1<https://github.com/aheward/TestFactory/pull/1>.

**Comment by aheward** [comment]
Primarily because it's been several years since I worked with these and I
didn't imagine that anyone else still was, either.

You think I should update them?

Abe

**Comment by Chuckv** [comment]
Might as well, or I can fork it and update if it no longer makes sense to
have it under rsmart

**Comment by aheward** [comment]
Hi Chuck! Please do that! It definitely does not make sense for this to be
under rSmart or Kuali any longer. They certainly don't care about it!

Thanks! If you need any help from me then let me know.

Abe

**Pull request merged**
